#!/usr/bin/env bash
# 9. To file, or not to file

file="school"

# file ?
if [ -e "$file" ]; then

  echo "school file exists"

  # empty ?
  if [ ! -s "$file" ]; then
    echo "school file is empty"

    # regular ?
    if [ -f "$file" ]; then
      echo "school is a regular file"
    fi  

  else

    echo "school file is not empty"

    # regular?
    if [ -f "$file" ]; then
      echo "school is a regular file"
    fi  
  
  fi

else
  
  echo "school file does not exist"

fi
